### ISSUE TITLE
something wrong when changed to another kind of lesion

### ISSUE THREAD

**Issue by llmir** [xiangwenliu/IDRiD-Lesion-Segmentation#2]
Traceback (most recent call last):
  File "train_main.py", line 492, in <module>
    tf.app.run()
  File "/home/mir/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_main.py", line 416, in main
    train_sauc = roc_auc_score(temp_train_annotations, np.nan_to_num(temp_tra_positive_prob))
  File "/home/mir/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 356, in roc_auc_score
    sample_weight=sample_weight)
  File "/home/mir/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/metrics/base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/mir/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 324, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

does anyone konws how to solve this error，thx！

**Comment by HimanshuAgarwal022** [comment]
same issue for me
